site_name: Polygon docs
site_author: Polygon Labs
copyright: Copyright &copy; 2023 Polygon Labs
repo_name: Polygon docs
repo_url: https://github.com/0xPolygon/polygon-docs
edit_uri: edit/main/docs/
#remote_branch: gh-pages
#remote_name: gh-deploy

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: white
      accent: purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      accent: purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  language: en
  favicon: img/favicon.ico
  logo: img/logo.png
  features:
    - search.suggest
    - search.highlight
    - search.share
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.expansion
    - navigation.integration
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.sections
    - navigation.path
    - navigation.top
    - navigation.footer
    - toc.follow
    - content.code.copy
    - content.action.edit

nav:
  - Home: index.md
  - CDK:
      - Welcome: 
        - cdk/index.md # marketing landing page
      - Get started:
        - Overview: cdk/get-started/overview.md
        - Quickstart:
          - Validium: cdk/get-started/quickstart-validium.md
          - Rollup: cdk/get-started/quickstart-rollup.md
        - Deploy:
          - Validium: cdk/get-started/deploy-validium.md
          - Rollup: cdk/get-started/deploy-rollup.md
      - How to: 
        - Manage policies - allowlists, denylists: cdk/how-to/manage-allowlists.md
      #- Architecture:
      - Specification:
        - Validium vs rollup: cdk/specification/validium-vs-rollup.md
        - Performance benchmarks: cdk/specification/performance-benchmarks.md
      - Concepts:
        - Data availability: cdk/concepts/dac.md
     # - API:
      - Troubleshooting:
        - CDK component repos: cdk/troubleshooting/component-repos.md
  - zkEVM:
      - zkEVM/index.md # marketing landing page
      - Get started:
        - Welcome: zkEVM/welcome.md
        - Quickstart:
          - Connecting to zkEVM: zkEVM/connect-wallet.md
          - Using Polygon faucet: zkEVM/zkevm-faucet.md
          - Bridging assets to zkEVM: zkEVM/bridge-to-zkevm.md
        - Setup nodes:
          - Setup local zkNode: zkEVM/setup-local-node.md
          - Setup production zkNode: zkEVM/setup-production-node.md
        - Deploy full zkEVM:
          - Start here: zkEVM/deployzkevm/step1-fullzkevm.md
          - Install dependencies: zkEVM/deployzkevm/step2-fullzkevm.md
          - Create wallets: zkEVM/deployzkevm/step3-fullzkevm.md
          - Deploy zkNode: zkEVM/deployzkevm/step4-fullzkevm.md
          - Configure prover: zkEVM/deployzkevm/step5-fullzkevm.md
          - Activate forced transactions: zkEVM/deployzkevm/step6-fullzkevm.md
          - Setup a Goërli node: zkEVM/deployzkevm/setup-goerlinode.md
      - How to:
        - Write a contract: zkEVM/autocode-smart-contract.md
        - Deploy a contract with Foundry: zkEVM/using-foundry.md
        - Deploy a contract with Hardhat: zkEVM/using-hardhat.md
        - Verify a contract: zkEVM/verify-smart-contract.md
      - Architectural design:
        - Architecture: zkEVM/architecture/architecture.md
        - zkEVM Protocol:
          - Introduction: zkEVM/protocol/introduction.md
          - State management: zkEVM/protocol/state-management.md
          - Trasaction life cycle:
            - Submit transactions: zkEVM/protocol/submit-trasaction.md
            - Transaction execution: zkEVM/protocol/transaction-execution.md
            - Transaction batching: zkEVM/protocol/transaction-batching.md
            - Batch sequencing: zkEVM/protocol/batch-sequencing.md
            - Batch aggregation: zkEVM/protocol/batch-aggregation.md
          - Incentive mechanism: zkEVM/protocol/incentive-mechanism.md
          - Protocol upgradability: zkEVM/protocol/upgradability.md
          - Admin role and governance: zkEVM/protocol/admin-role.md
          - Upgrade process: zkEVM/protocol/zkevm-upgrades-process.md
          - Security council: zkEVM/protocol/security-council.md
          - Malfunction resistance:
            - Force batches: zkEVM/protocol/sequencer-resistance.md
            - Force verification: zkEVM/protocol/aggregator-resistance.md
            - Emergency state: zkEVM/protocol/emergency-state.md
          - zkEVM bridge:
            - Bridge introduction: zkEVM/protocol/zkevm-bridge.md
            - Exit trees: zkEVM/protocol/exit-tree.md
            - Smart contracts: zkEVM/protocol/bridge-smart-contract.md
            - Flow of assets: zkEVM/protocol/flow-of-assets.md
          - LXLY bridge: zkEVM/protocol/lxly-bridge.md
        - zkNode: zkEVM/zknode/zknode-overview.md
        - zkProver:
          - zkProver Overview: zkEVM/zkprover/zkprover-overview.md
          - Main state machaine: 
            - Introducing Main SM: zkEVM/zkprover/intro-main-sm.md
            - As a processor: zkEVM/zkprover/the-processor.md
          - STARK recursion:
            - Introducing STARK recursion: zkEVM/zkprover/intro-stark-recursion.md
            - Proving tools and techniques: zkEVM/zkprover/proving-tools.md
            - Composition, Recursion and Aggregation: zkEVM/zkprover/stark-recursion-detail.md
            - Recursion sub-process: zkEVM/zkprover/recursion-sub-process.md
            - Proving architecture: zkEVM/zkprover/proving-architecture.md
            - CIRCOM in zkProver: zkEVM/zkprover/circom-in-zkprover.md
            - Proving setup phase: zkEVM/zkprover/proving-setup-phase.md
            - Intermediate steps: zkEVM/zkprover/intermediate-recursion.md
            - Final recursion step: zkEVM/zkprover/final-recursion-step.md
            - Proof generation phase: zkEVM/zkprover/proof-generation-phase.md
      - Specifications:
        - EVM vs. zkEVM: zkEVM/specifications/evm-differences.md
      - Concepts:
        - EVM basics: zkEVM/concepts/evm-basics.md
        - mFibonnaci state machine:
          - Design approach: zkEVM/concepts/mfibonacci.md
          - An example: zkEVM/concepts/mfibonacci-example.md
          - Commitment scheme: zkEVM/concepts/commitment-scheme.md
          - Verification scheme: zkEVM/concepts/verification-scheme.md
          - PIL-STARK process: zkEVM/concepts/pil-stark.md
          - PIL-STARK demo: zkEVM/concepts/pil-stark-demo.md
        - Generic state machine: 
          - Generic SM introduction: zkEVM/concepts/intro-generic-sm.md
          - Execution trace: zkEVM/concepts/exec-trace-correct.md
          - Ending programs: zkEVM/concepts/ending-program.md
          - Program counter: zkEVM/concepts/program-counter.md
          - Plookup: zkEVM/concepts/plookup.md
        - CIRCOM: zkEVM/concepts/circom-intro-brief.md
      - Troubleshooting:
        - Disclosures: zkEVM/troubleshooting/risk-disclosures.md
  - PoS:
      - pos/index.md # marketing landing page
      - Get started: 
        - Get started: pos/get-started/index.md
        - Building on Polygon: pos/get-started/building-on-polygon.md
      - How to:
        - How to: pos/how-to/index.md
        - Operate a node:
          - Operate a node: pos/how-to/operating/index.md
          - Full node:
            - Full node: pos/how-to/operating/full-node/index.md
            - Manual install: pos/how-to/operating/full-node/manual-install.md
            - Ansible: pos/how-to/operating/full-node/ansible.md
            - Docker: pos/how-to/operating/full-node/docker.md
            - Google cloud: pos/how-to/operating/full-node/gcp.md
          - Validator node:
            - Validator node: pos/how-to/operating/validator-node/index.md
            - Manual install: pos/how-to/operating/validator-node/manual-install.md
            - Ansible: pos/how-to/operating/validator-node/ansible.md
            - Staking: pos/how-to/operating/validator-node/staking.md
          - Access node: pos/how-to/operating/access-node.md
          - Archive node: pos/how-to/operating/archive-node.md
          - Erigon node: pos/how-to/operating/erigon-node.md
        - Bridge layers:
          - Bridge layers: pos/how-to/bridging/index.md
          - Ethereum-Polygon:
            - Ethereum-Polygon: pos/how-to/bridging/ethereum-polygon/index.md
            - Ethereum to MATIC: pos/how-to/bridging/ethereum-polygon/ethereum-to-matic.md
            - MATIC to Ethereum: pos/how-to/bridging/ethereum-polygon/matic-to-ethereum.md
            - Submit mapping request: pos/how-to/bridging/ethereum-polygon/submit-mapping-request.md
          - L1-L2 communication:
            - L1-L2 communication: pos/how-to/bridging/l1-l2-communication/index.md
            - State transfer: pos/how-to/bridging/l1-l2-communication/state-transfer.md
            - Bridging with FxPortal: pos/how-to/bridging/l1-l2-communication/fx-portal.md
        - Work with smart contracts:
          - Work with smart contracts: pos/how-to/smart-contracts/index.md
          - Alchemy: pos/how-to/smart-contracts/alchemy.md
          - ChainIDE: pos/how-to/smart-contracts/chainide.md
          - ChainStack: pos/how-to/smart-contracts/chainstack.md
          - GetBlock: pos/how-to/smart-contracts/getblock.md
          - QuickNode: pos/how-to/smart-contracts/quicknode.md
          - SmartPress: pos/how-to/smart-contracts/smartpress.md
          - ThirdWeb: pos/how-to/smart-contracts/thirdweb.md
        - Polygon DID: pos/how-to/polygon-did.md
      - Architecture:
          - pos/architecture/index.md
          - Bor:
            - Bor: pos/architecture/bor/index.md
            - Consensus: pos/architecture/bor/consensus.md
            - State sync: pos/architecture/bor/state-sync.md
            - Network configuration: pos/architecture/bor/network-config.md
            - Snapshots: pos/architecture/bor/snapshots.md
            - Commands: pos/architecture/bor/commands.md
          - Heimdall:
            - Heimdall: pos/architecture/heimdall/index.md
            - Checkpoint: pos/architecture/heimdall/checkpoint.md
            - Governance: pos/architecture/heimdall/governance.md
            - Key management: pos/architecture/heimdall/key-management.md
            - Stdtx: pos/architecture/heimdall/stdtx.md
            - Modules:
              - Modules: pos/architecture/heimdall/modules/index.md
              - Ante handler: pos/architecture/heimdall/modules/antehandler.md
              - Auth: pos/architecture/heimdall/modules/auth.md
              - Bank: pos/architecture/heimdall/modules/bank.md
              - Bor: pos/architecture/heimdall/modules/bor.md
              - Chain manager: pos/architecture/heimdall/modules/chain-manager.md
              - Checkpoint: pos/architecture/heimdall/modules/checkpoint.md
              - Staking: pos/architecture/heimdall/modules/staking.md
              - Topup: pos/architecture/heimdall/modules/topup.md
            - FAQ: pos/architecture/heimdall/faq.md
      - Specification:
          - pos/spec/index.md
      - Concepts:
          - Concepts: pos/concepts/index.md
          - Tokens:
            - Tokens: pos/concepts/tokens/index.md
            - POL: pos/concepts/tokens/pol.md
            - MATIC: pos/concepts/tokens/matic.md
          - Transactions:
            - Transactions: pos/concepts/transactions/index.md
            - EIP-1559: pos/concepts/transactions/eip-1559.md
            - EIP-4337: pos/concepts/transactions/eip-4337.md
            - Meta-transactions: pos/concepts/transactions/meta-transactions.md
      - API:
          - pos/api/index.md
  - Miden:
      - Overview: miden/index.md
      - Miden playground: https://0xpolygonmiden.github.io/examples/
      - Miden zkRollup docs: https://0xpolygonmiden.github.io/miden-base/introduction.html
      - Miden VM docs: https://0xpolygonmiden.github.io/miden-vm/
  - Tools: 
      - tools/index.md
      - Using Web3Modal SDK: tools/using-web3modal.md
  - Tutorials:
      - Tutorials: tutorials/index.md
      - Build a Validium-based App-chain: tutorials/build-validium.md
      - Deploy a zkEVM Rollup: tutorials/deploy-zkEVM.md
      - Deploy a Miden Rollup: tutorials/deploy-miden.md
      - Build a dApp on zkEVM: tutorials/build-zkEVM-dapp.md
      - Run a PoS node: tutorials/run-pos-node.md
      - Become a PoS Validator: tutorials/become-pos-validator.md

extra:
  generator: false
  analytics:
  #  provider: google
  #  property: G-XXXXXXXXXX
  #  feedback:  # feedback form only works when Google Analytics is set up and working
  #    title: Was this page helpful?
  #    ratings:
  #      - icon: fontawesome/regular/face-grin-stars
  #        name: This page was helpful
  #        data: 1
  #        note: >-
  #          Thanks for your feedback!
  #      - icon: fontawesome/regular/face-grimace
  #        name: This page could be improved
  #        data: 0
  #        note: >-
  #          Thanks for your feedback! Help us improve this page by
  #          using our <a href="..." target="_blank" rel="noopener">feedback form</a>.
  social:
    - icon: fontawesome/solid/circle-question
      link: https://support.polygon.technology/support/solutions
    - icon: fontawesome/solid/globe
      link: https://polygon.technology/
    - icon: fontawesome/brands/github
      link: https://github.com/0xPolygon/polygon-docs
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

extra_css:
  - _site_essentials/stylesheets/extra.css
  - _site_essentials/stylesheets/section-nav.css
  - https://fonts.googleapis.com/icon?family=Material+Icons

markdown_extensions:
  - toc:
      permalink: true
      permalink_title: Link to this section
      toc_depth: 4
  - codehilite
  - markdown_include.include:
      base_path: docs
  - admonition
  - footnotes
  - def_list
  - attr_list
  - abbr
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.keys
  - pymdownx.details
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.caret
  - meta
  - smarty
  - pymdownx.extra

plugins:
  - search
  - open-in-new-tab
#  - git-revision-date-localized:
#      enable_creation_date: true
#      fallback_to_build_date: true
#  - git-committers:
#      repository: 0xPolygon/polygon-docs
#      #branch: main
#      exclude:
#        - README.md

validation:
  absolute_links: warn
