name: Daily Merge Main to Dev

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at 00:00 UTC

jobs:
  merge-main-to-dev:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch latest changes
        run: git fetch origin

      - name: Merge main branch to dev branch
        run: git merge origin/main -m "Merge main branch to dev"

      - name: Push dev branch changes
        run: git push origin dev
